repos:
- repo: local
  hooks:
  - id: update-requirements-txt
    name: update-requirements-txt
    entry: pip
    args: [freeze, \>, requirements.txt]
    pass_filenames: false
    language: system
    types: [python]
    always_run: true
  - id: pylint
    name: pylint
    entry: pylint
    args: [locomotion]
    pass_filenames: false
    language: system
    types: [python]
    always_run: true
