quadruped:
  # Publish all joint states
  #joint_state_controller:
  #  type: joint_state_controller/JointStateController
  #  publish_rate: 60

  # controllers
  joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController

    joints:
      - FR_calf_joint
      - FR_thigh_joint
      - FR_hip_joint
      - FL_calf_joint
      - FL_thigh_joint
      - FL_hip_joint
      - RR_calf_joint
      - RR_thigh_joint
      - RR_hip_joint
      - RL_calf_joint
      - RL_thigh_joint
      - RL_hip_joint

    gains:
      FR_calf_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      FR_thigh_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      FR_hip_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      FL_calf_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      FL_thigh_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      FL_hip_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      RR_calf_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      RR_thigh_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      RR_hip_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      RL_calf_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      RL_thigh_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      RL_hip_joint: {p: 200, d: 1, i: 30, i_clamp: 100}


